### ISSUE TITLE
[TEALIUM SWIFT BUG]: 

### ISSUE THREAD

**Issue by syahrizan05** [Tealium/tealium-react-native#99]
**Your Environment**
*Fill out as appropriate.*
iOS Version(s) [11]:
Xcode version [Xcode> About Xcode  (13.1)]:
Tealium Swift library version [2.1.3]: 
Dependency manager [CocoaPods]:
Dependency manager version: 

**Describe the bug**
Cannot compile IOS due to error 'TealiumSwift/TealiumSwift-Swift.h' file not found

**Does a workaround exist?**
No

**To Reproduce**
1. run tealium-react-native
2. change Podfile to include   pod 'tealium-swift' 
3. cd ios && pod install
4. on xcode click on build

**Expected behavior**
app built and can run on simulator

**Screenshots**
![image](https://user-images.githubusercontent.com/37117398/143191116-8bf7cee1-3052-4836-8454-a51a43300e69.png)

**Additional context**

**Comment by craigrouse** [comment]
@syahrizan05 We're looking into this and hopefully will have a resolution shortly. If you want to proceed with the older version, you should be able to see console logs in the Xcode debugger.

**Comment by craigrouse** [comment]
@syahrizan05 @KirilVelichkov we have found a solution and an update will be available very soon. The good news is that it won't require you to upgrade the React Native plugin version - the fix is in the Tealium Swift package, so you'll just need to reinstall the plugin, and it should work. We'll confirm here once the fix is released.

**Comment by syahrizan05** [comment]
Thank you. Let us know when the fix is released. 

Also could you please provide me with the sample code using React Native 1.x . The link for sample app on the documentation (https://github.com/Tealium/tealium-react-native/tree/master/TealiumSampleApp) is broken.

Thank you

**Comment by nstoilov** [comment]
Hello, when installing tealium-react-native: 2.1.3, the version of tealium-swift that is installed is 2.5.0. and the problem in the issue is still there. Is 2.5.1 available? 

Thanks!

**Comment by Enricoza** [comment]
Hi @nstoilov, 2.5.1 is available.
Have you tried running  `pod install --repo-update` or `pod update tealium-swift`?

**Comment by nstoilov** [comment]
Thanks, this worked and the iOS build is now successful.
